language: ruby
before_install:
  - gem update --system
rvm:
  - "2.0"
#  - "2.1.0"
addons:
  apt:
    packages:
      - libqtwebkit-dev
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/site.example.yml config/site.yml
  - bundle exec rake db:migrate RAILS_ENV=test
script: 
  - bundle exec rubocop
  - xvfb-run bundle exec rake
